const data_base = {
  'INYECTABLES': {
    titulo: 'INYECTABLES',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: 'PRODUCCIÓN : 2211 INYECTABLES',
    centro_costo_hddn: '8',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Producto Terminado',
    consumo: 'checked',
    cuenta_compras: '20111112 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Medicamentos Veterinarios L8',
    cuenta_compras_hddn: '4790',
    cuenta_variacion: '61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8',
    cuenta_variacion_hddn: '5865',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '2',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '51142700',
    cuenta_costo_productos_vendidos: '69221113 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Inyectables L8',
    cuenta_costo_productos_vendidos_hddn: '6249',
    cuenta_activo: '21111003 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Inyectables L8',
    cuenta_activo_hddn: '4812',
    cuenta_ingresos: '70221113 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Inyectables L8',
    cuenta_ingresos_hddn: '6363',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911112 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Inyectables L8',
    cuenta_desviacion_desensamblaje_hddn: '6663',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921117 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Inyectables',
    cuenta_desviacion_cantidad_produccion_hddn: '6820',
    cuenta_desviacion_precio_produccion: '69921117 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Inyectables',
    cuenta_desviacion_precio_produccion_hddn: '6820',
    cuenta_desviacion_precio_compra: '69921117 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Inyectables',
    cuenta_desviacion_precio_compra_hddn: '6820',
  },
  'LIQUIDOS' : {
    titulo: 'LIQUIDOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: 'PRODUCCIÓN : 2231 LIQUIDOS',
    centro_costo_hddn: '10',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Materia Prima',
    consumo: 'checked',
    cuenta_compras: '20111112 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Medicamentos Veterinarios L8',
    cuenta_compras_hddn: '4790',
    cuenta_variacion: '61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8',
    cuenta_variacion_hddn: '5865',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '2',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221116 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Líquidos L8',
    cuenta_costo_productos_vendidos_hddn: '6252',
    cuenta_activo: '21111007 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Líquidos L8',
    cuenta_activo_hddn: '4816',
    cuenta_ingresos: '70221116 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Líquidos L8',
    cuenta_ingresos_hddn: '6366',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911115 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Líquidos L8',
    cuenta_desviacion_desensamblaje_hddn: '6666',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921122 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT NAC Liquidos',
    cuenta_desviacion_cantidad_produccion_hddn: '6825',
    cuenta_desviacion_precio_produccion: '69921122 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT NAC Liquidos',
    cuenta_desviacion_precio_produccion_hddn: '6825',
    cuenta_desviacion_precio_compra: '69921122 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT NAC Liquidos',
    cuenta_desviacion_precio_compra_hddn: '6825',
  },
  'BULK_PRODUCTOS_INTERMEDIOS' : {
    titulo: 'BULK_PRODUCTOS_INTERMEDIOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'BULK',
    tipo_producto_hddn: '22',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: '',
    centro_costo_hddn: '',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Materia Prima',
    consumo: 'checked',
    cuenta_compras: '60111112 PE-Compras-L2 : PE-Mercaderias 60-L3 : PE-Mercaderias 60-L4 : PE-Mercaderias 60111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Compra MERC - Medicamentos Veterinarios L8',
    cuenta_compras_hddn: '5793',
    cuenta_variacion: '61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8',
    cuenta_variacion_hddn: '5865',
    tipo_existencia: '09 Subproductos',
    tipo_existencia_hddn: '9',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '09',
    cod_tipo_existencia_hddn: '09',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8',
    cuenta_costo_productos_vendidos_hddn: '6228',
    cuenta_activo: '23111111 PE-Productos en proceso-L2 : PE-Productos en proceso 23-L3 : PE-Productos en proceso 23-L4 : PE-Costo 23111-L5 : PE-Productos en Proceso L6 : PE-Productos en Proceso L7 : PE-PP Bulk L8',
    cuenta_activo_hddn: '5051',
    cuenta_ingresos: '70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8',
    cuenta_ingresos_hddn: '6340',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911117 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Bulk L8',
    cuenta_desviacion_desensamblaje_hddn: '6668',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_produccion_hddn: '6679',
    cuenta_desviacion_precio_produccion: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_produccion_hddn: '6686',
    cuenta_desviacion_precio_compra: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_compra_hddn: '6686',
  },
  'SOLIDOS' : {
    titulo: 'SOLIDOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: 'PRODUCCIÓN : 2251 SOLIDOS',
    centro_costo_hddn: '12',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Materia Prima',
    consumo: 'checked',
    cuenta_compras: '',
    cuenta_compras_hddn: '',
    cuenta_variacion: '',
    cuenta_variacion_hddn: '',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '02',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221117 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Sólidos L8',
    cuenta_costo_productos_vendidos_hddn: '6253',
    cuenta_activo: '21111008 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Sólidos L8',
    cuenta_activo_hddn: '4817',
    cuenta_ingresos: '70221117 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Sólidos L8',
    cuenta_ingresos_hddn: '6367',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '',
    cuenta_variacion_tipo_cambio_hddn: '',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911116 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Sólidos L8',
    cuenta_desviacion_desensamblaje_hddn: '6667',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921121 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT NAC Sólidos',
    cuenta_desviacion_cantidad_produccion_hddn: '6824',
    cuenta_desviacion_precio_produccion: '69921121 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT NAC Sólidos',
    cuenta_desviacion_precio_produccion_hddn: '6824',
    cuenta_desviacion_precio_compra: '69921121 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT NAC Sólidos',
    cuenta_desviacion_precio_compra_hddn: '6824',
  },
  'SEMISOLIDOS' : {
    titulo: 'SEMISOLIDOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: 'PRODUCCIÓN : 2221 SEMISOLIDOS',
    centro_costo_hddn: '9',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Producto Terminado',
    consumo: 'checked',
    cuenta_compras: '',
    cuenta_compras_hddn: '',
    cuenta_variacion: '',
    cuenta_variacion_hddn: '',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '02',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221112 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Semisólidos L8',
    cuenta_costo_productos_vendidos_hddn: '6248',
    cuenta_activo: '21111002 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Semisólidos L8',
    cuenta_activo_hddn: '4811',
    cuenta_ingresos: '70221112 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Semisólidos L8',
    cuenta_ingresos_hddn: '6362',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911111 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Semisólidos L8',
    cuenta_desviacion_desensamblaje_hddn: '6662',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921116 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio : PE Desviación costo estándar -PT NAC Semisólidos',
    cuenta_desviacion_cantidad_produccion_hddn: '6819',
    cuenta_desviacion_precio_produccion: '69921116 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio : PE Desviación costo estándar -PT NAC Semisólidos',
    cuenta_desviacion_precio_produccion_hddn: '6819',
    cuenta_desviacion_precio_compra: '69921116 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio : PE Desviación costo estándar -PT NAC Semisólidos',
    cuenta_desviacion_precio_compra_hddn: '6819',
  },
  'POLVOS' : {
    titulo: 'POLVOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: 'PRODUCCIÓN : 2261 POLVOS',
    centro_costo_hddn: '32',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'No Definido',
    consumo: 'checked',
    cuenta_compras: '',
    cuenta_compras_hddn: '',
    cuenta_variacion: '',
    cuenta_variacion_hddn: '',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '02',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221114 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Polvos L8',
    cuenta_costo_productos_vendidos_hddn: '6250',
    cuenta_activo: '21111005 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Polvos L8',
    cuenta_activo_hddn: '4814',
    cuenta_ingresos: '70221114 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Polvos L8',
    cuenta_ingresos_hddn: '6364',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911113 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Polvos L8',
    cuenta_desviacion_desensamblaje_hddn: '6664',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921119 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio : PE Desviación costo estándar - PT Polvos',
    cuenta_desviacion_cantidad_produccion_hddn: '6822',
    cuenta_desviacion_precio_produccion: '69921119 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio : PE Desviación costo estándar - PT Polvos',
    cuenta_desviacion_precio_produccion_hddn: '6822',
    cuenta_desviacion_precio_compra: '69921119 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio : PE Desviación costo estándar - PT Polvos',
    cuenta_desviacion_precio_compra_hddn: '6822',
  },
  'PRODUCTOS_INTERMEDIOS_TERCEROS' : {
    titulo: 'PRODUCTOS_INTERMEDIOS_TERCEROS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: '',
    centro_costo_hddn: '',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'No Definido',
    consumo: 'checked',
    cuenta_compras: '',
    cuenta_compras_hddn: '',
    cuenta_variacion: '',
    cuenta_variacion_hddn: '',
    tipo_existencia: '',
    tipo_existencia_hddn: '',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '',
    cod_tipo_existencia_hddn: '',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8',
    cuenta_costo_productos_vendidos_hddn: '6228',
    cuenta_activo: '23111112 PE-Productos en proceso-L2 : PE-Productos en proceso 23-L3 : PE-Productos en proceso 23-L4 : PE-Costo 23111-L5 : PE-Productos en Proceso L6 : PE-Productos en Proceso L7 : PE-PP Intermedio Tercero L8',
    cuenta_activo_hddn: '5052',
    cuenta_ingresos: '70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8',
    cuenta_ingresos_hddn: '6340',
    cuenta_desviacion_precio: '',
    cuenta_desviacion_precio_hddn: '',
    cuenta_desviacion_cantidad: '',
    cuenta_desviacion_cantidad_hddn: '',
    cuenta_variacion_tipo_cambio: '',
    cuenta_variacion_tipo_cambio_hddn: '',
    cuenta_rechazo: '23911118 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - PIT L8',
    cuenta_rechazo_hddn: '6669',
    cuenta_wip: '23211112 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Intermedio Tercero WIP L8',
    cuenta_wip_hddn: '6656',
    cuenta_desviacion_desensamblaje: '23911118 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - PIT L8',
    cuenta_desviacion_desensamblaje_hddn: '6669',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '',
    cuenta_desviacion_cantidad_produccion_hddn: '',
    cuenta_desviacion_precio_produccion: '',
    cuenta_desviacion_precio_produccion_hddn: '',
    cuenta_desviacion_precio_compra: '',
    cuenta_desviacion_precio_compra_hddn: '',
  },
  'AEROSOL' : {
    titulo: 'AEROSOL',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: '',
    centro_costo_hddn: '',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Producto Terminado',
    consumo: 'checked',
    cuenta_compras: '20111112 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Medicamentos Veterinarios L8',
    cuenta_compras_hddn: '4790',
    cuenta_variacion: '61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8',
    cuenta_variacion_hddn: '5865',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '2',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221118 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Aerosol L8',
    cuenta_costo_productos_vendidos_hddn: '6254',
    cuenta_activo: '21111001 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Aerosol L8',
    cuenta_activo_hddn: '4810',
    cuenta_ingresos: '70221118 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Aerosol L8',
    cuenta_ingresos_hddn: '6368',
    cuenta_desviacion_precio: '',
    cuenta_desviacion_precio_hddn: '',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '6993111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '23911119 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Aerosol L8',
    cuenta_rechazo_hddn: '6670',
    cuenta_wip: '23111111 PE-Productos en proceso-L2 : PE-Productos en proceso 23-L3 : PE-Productos en proceso 23-L4 : PE-Costo 23111-L5 : PE-Productos en Proceso L6 : PE-Productos en Proceso L7 : PE-PP Bulk L8',
    cuenta_wip_hddn: '5051',
    cuenta_desviacion_desensamblaje: '23911119 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Aerosol L8',
    cuenta_desviacion_desensamblaje_hddn: '6670',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921123 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar -PT NAC Aerosol',
    cuenta_desviacion_cantidad_produccion_hddn: '6826',
    cuenta_desviacion_precio_produccion: '69921123 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar -PT NAC Aerosol',
    cuenta_desviacion_precio_produccion_hddn: '6826',
    cuenta_desviacion_precio_compra: '69921123 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar -PT NAC Aerosol',
    cuenta_desviacion_precio_compra_hddn: '6826',
  },
  'ALIMENTOS_ACTIVOS_BIOLOGICOS' : {
    titulo: 'ALIMENTOS_ACTIVOS_BIOLOGICOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: '',
    centro_costo_hddn: '',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Materia Prima',
    consumo: 'checked',
    cuenta_compras: 'Activo de inventario',
    cuenta_compras_hddn: '214',
    cuenta_variacion: 'Anticipos pagados',
    cuenta_variacion_hddn: '118',
    tipo_existencia: '',
    tipo_existencia_hddn: '',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '',
    cod_tipo_existencia_hddn: '',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: 'Activo de inventario',
    cuenta_costo_productos_vendidos_hddn: '214',
    cuenta_activo: 'Anticipos pagados',
    cuenta_activo_hddn: '118',
    cuenta_ingresos: '60991111 Compras acumuladas',
    cuenta_ingresos_hddn: '112',
    cuenta_desviacion_precio: '',
    cuenta_desviacion_precio_hddn: '',
    cuenta_desviacion_cantidad: '',
    cuenta_desviacion_cantidad_hddn: '',
    cuenta_variacion_tipo_cambio: '',
    cuenta_variacion_tipo_cambio_hddn: '',
    cuenta_rechazo: '',
    cuenta_rechazo_hddn: '',
    cuenta_wip: '23111111 PE-Productos en proceso-L2 : PE-Productos en proceso 23-L3 : PE-Productos en proceso 23-L4 : PE-Costo 23111-L5 : PE-Productos en Proceso L6 : PE-Productos en Proceso L7 : PE-PP Bulk L8',
    cuenta_wip_hddn: '5051',
    cuenta_desviacion_desensamblaje: '',
    cuenta_desviacion_desensamblaje_hddn: '',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '',
    cuenta_desviacion_cantidad_produccion_hddn: '',
    cuenta_desviacion_precio_produccion: '',
    cuenta_desviacion_precio_produccion_hddn: '',
    cuenta_desviacion_precio_compra: '',
    cuenta_desviacion_precio_compra_hddn: '',
  },
  'PRODUCTO_PILOTO' : {
    titulo: 'PRODUCTO_PILOTO',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : ENSAYOS Y PILOTOS',
    almacen_hddn: '71',
    centro_costo: 'COMERCIAL : 5501 INVESTIGACION Y DESARROLLO',
    centro_costo_hddn: '26',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Materia Prima',
    consumo: 'checked',
    cuenta_compras: '',
    cuenta_compras_hddn: '',
    cuenta_variacion: '',
    cuenta_variacion_hddn: '',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '2',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8',
    cuenta_costo_productos_vendidos_hddn: '6228',
    cuenta_activo: '65711113 PE-Otros gastos de gestion-L2 : PE-Investigación y Desarrollo L3 : PE-Investigación y Desarrollo L4 : PE-Investigación y Desarrollo L5 : PE-Investigación y Desarrollo L6 : PE-Investigación y Desarrollo L7 : PE-Pruebas Pilotos L8',
    cuenta_activo_hddn: '6161',
    cuenta_ingresos: '70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8',
    cuenta_ingresos_hddn: '6686',
    cuenta_desviacion_precio: '',
    cuenta_desviacion_precio_hddn: '',
    cuenta_desviacion_cantidad: '',
    cuenta_desviacion_cantidad_hddn: '',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911116 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Sólidos L8',
    cuenta_desviacion_desensamblaje_hddn: '6667',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '',
    cuenta_desviacion_cantidad_produccion_hddn: '',
    cuenta_desviacion_precio_produccion: '',
    cuenta_desviacion_precio_produccion_hddn: '',
    cuenta_desviacion_precio_compra: '',
    cuenta_desviacion_precio_compra_hddn: '',
    /*cuenta_desviacion_cantidad_produccion: '65711113 PE-Otros gastos de gestion-L2 : PE-Investigación y Desarrollo L3 : PE-Investigación y Desarrollo L4 : PE-Investigación y Desarrollo L5 : PE-Investigación y Desarrollo L6 : PE-Investigación y Desarrollo L7 : PE-Pruebas Pilotos L8',
    cuenta_desviacion_cantidad_produccion_hddn: '6161',
    cuenta_desviacion_precio_produccion: '65711113 PE-Otros gastos de gestion-L2 : PE-Investigación y Desarrollo L3 : PE-Investigación y Desarrollo L4 : PE-Investigación y Desarrollo L5 : PE-Investigación y Desarrollo L6 : PE-Investigación y Desarrollo L7 : PE-Pruebas Pilotos L8',
    cuenta_desviacion_precio_produccion_hddn: '6161',
    cuenta_desviacion_precio_compra: '65711113 PE-Otros gastos de gestion-L2 : PE-Investigación y Desarrollo L3 : PE-Investigación y Desarrollo L4 : PE-Investigación y Desarrollo L5 : PE-Investigación y Desarrollo L6 : PE-Investigación y Desarrollo L7 : PE-Pruebas Pilotos L8',
    cuenta_desviacion_precio_compra_hddn: '6161',*/
  },
  'SOLUCIONES_TOPICAS' : {
    titulo: 'SOLUCIONES_TOPICAS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: 'PRODUCCIÓN : 2241 SOLUCIONES TOPICAS',
    centro_costo_hddn: '11',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Producto Terminado',
    consumo: 'checked',
    cuenta_compras: '',
    cuenta_compras_hddn: '',
    cuenta_variacion: '',
    cuenta_variacion_hddn: '',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '2',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221115 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Costo de Ventas - PT NAC Soluciones TópicasL8',
    cuenta_costo_productos_vendidos_hddn: '6251',
    cuenta_activo: '21111006 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Soluciones Tópicas L8',
    cuenta_activo_hddn: '4815',
    cuenta_ingresos: '70221115 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Venta L7 : PE-Ventas de PT - NAC Tópicas L8',
    cuenta_ingresos_hddn: '6365',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911114 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Soluciones Tópicas',
    cuenta_desviacion_desensamblaje_hddn: '6665',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921120 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Soluciones Tópicas',
    cuenta_desviacion_cantidad_produccion_hddn: '6823',
    cuenta_desviacion_precio_produccion: '69921120 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Soluciones Tópicas',
    cuenta_desviacion_precio_produccion_hddn: '6823',
    cuenta_desviacion_precio_compra: '69921120 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Soluciones Tópicas',
    cuenta_desviacion_precio_compra_hddn: '6823',
  },
  'MUESTRAS_MEDICAS' : {
    titulo: 'MUESTRAS_MEDICAS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'PRODUCTO TERMINADO',
    tipo_producto_hddn: '16',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: '',
    centro_costo_hddn: '',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Producto Terminado',
    consumo: 'checked',
    cuenta_compras: '20111112 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Medicamentos Veterinarios L8',
    cuenta_compras_hddn: '4790',
    cuenta_variacion: '61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8',
    cuenta_variacion_hddn: '5865',
    tipo_existencia: '02 Productos Terminados',
    tipo_existencia_hddn: '2',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '02',
    cod_tipo_existencia_hddn: '02',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69221131 PE-Costo de ventas-L2 : PE-Productos terminados 6-L3 : PE-Productos terminados - Venta local 69-L4 : PE-Terceros 69221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Muestra Médica L7 : PE-Costo de Ventas - Muestra PT NAC L8',
    cuenta_costo_productos_vendidos_hddn: '6255',
    cuenta_activo: '21111004 PE-Productos terminados-L2 : PE-Productos terminados 21-L3 : PE-Productos terminados 21-L4 : PE-Costo 21111-L5 : PE-Productos Terminados Costo L6 : PE-Productos Terminados Costo L7 : PE-PT Muestrás Médicas L8',
    cuenta_activo_hddn: '4813',
    cuenta_ingresos: '70221131 PE-Ventas-L2 : PE-Productos terminados 7-L3 : PE-Productos terminados - venta local 702-L4 : PE-Terceros 70221-L5 : PE-Productos Terminados Nacional L6 : PE-Productos Terminados Nacional - Muestra Médica L7 : PE-Ventas - Muestra PT NAC L8',
    cuenta_ingresos_hddn: '6369',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '23911120 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Muestras médicas L8',
    cuenta_rechazo_hddn: '6671',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911120 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Muestras médicas L8',
    cuenta_desviacion_desensamblaje_hddn: '6671',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69921118 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Muestras Médicas',
    cuenta_desviacion_cantidad_produccion_hddn: '6821',
    cuenta_desviacion_precio_produccion: '69921118 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Muestras Médicas',
    cuenta_desviacion_precio_produccion_hddn: '6821',
    cuenta_desviacion_precio_compra: '69921118 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - PT Muestras Médicas',
    cuenta_desviacion_precio_compra_hddn: '6821',
  },
  'PRODUCTO_INTERMEDIO_POLVOS' : {
    titulo: 'PRODUCTO_INTERMEDIO_POLVOS',
    subsidiaria: '2',
    inactivo: 'checked',
    metodo_calculo_costo: 'Estándar',
    metodo_calculo_costo_hddn: 'STANDARD',
    metodo_calculo_costo_indx: '2',
    tipo_producto: 'BULK',
    tipo_producto_hddn: '22',
    almacen: 'SEDE ATE : FABRICACIÓN',
    almacen_hddn: '65',
    centro_costo: '',
    centro_costo_hddn: '',
    soporte_oferta: 'checked',
    utiliza_deposito: 'checked',
    categoria_costo: 'Materia Prima',
    consumo: 'checked',
    cuenta_compras: '60111112 PE-Compras-L2 : PE-Mercaderias 60-L3 : PE-Mercaderias 60-L4 : PE-Mercaderias 60111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Compra MERC - Medicamentos Veterinarios L8',
    cuenta_compras_hddn: '5793',
    cuenta_variacion: '61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8',
    cuenta_variacion_hddn: '5865',
    tipo_existencia: '09 Subproductos',
    tipo_existencia_hddn: '9',
    catalogo_existencia: 'CUBSO',
    catalogo_existencia_hddn: '2',
    catalogo_existencia_indx: '6',
    metodo_valuacion: 'Promedio Ponderado',
    metodo_valuacion_hddn: '1',
    metodo_valuacion_indx: '7',
    //unidad_medida: '',
    //unidad_medida_hddn: '',
    cod_tipo_existencia: '09',
    cod_tipo_existencia_hddn: '09',
    cod_inventory_catalog: '2',
    cod_inventory_catalog_hddn: '2',
    cod_metodo_valuacion: '1',
    cod_metodo_valuacion_hddn: '1',
    //cod_unidad_medida: '',
    //cod_unidad_medida_hddn: '',
    cod_cubso: '-',
    cuenta_costo_productos_vendidos: '69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8',
    cuenta_costo_productos_vendidos_hddn: '6228',
    cuenta_activo: '23111111 PE-Productos en proceso-L2 : PE-Productos en proceso 23-L3 : PE-Productos en proceso 23-L4 : PE-Costo 23111-L5 : PE-Productos en Proceso L6 : PE-Productos en Proceso L7 : PE-PP Bulk L8',
    cuenta_activo_hddn: '5051',
    cuenta_ingresos: '70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8',
    cuenta_ingresos_hddn: '6340',
    cuenta_desviacion_precio: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_hddn: '6686',
    cuenta_desviacion_cantidad: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_hddn: '6679',
    cuenta_variacion_tipo_cambio: '69931111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio : PE Desviación costo estándar - Diferencia de cambio',
    cuenta_variacion_tipo_cambio_hddn: '6694',
    cuenta_rechazo: '69921115 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Rechazos',
    cuenta_rechazo_hddn: '6690',
    cuenta_wip: '23211111 PE-Productos en proceso-L2 : PE-Productos en proceso WIP 23-L3 : PE-Productos en proceso WIP 23-L4 : PE-Costo 23211-L5 : PE-Productos en Proceso WIP L6 : PE-Productos en Proceso WIP L7 : PE-PP Bulk WIP L8',
    cuenta_wip_hddn: '6655',
    cuenta_desviacion_desensamblaje: '23911117 PE-Productos en proceso-L2 : PE-Productos en proceso Rechazo 23-L3 : PE-Productos en proceso Rechazo 23-L4 : PE-Costo 239111-L5 : PE-PP Rechazo L6 : PE-PP Rechazo L7 : PE-PP Rechazo - Bulk L8',
    cuenta_desviacion_desensamblaje_hddn: '6668',
    programa_fiscal: 'IGV',
    programa_fiscal_hddn: '3',
    programa_fiscal_indx: '3',
    cuenta_desviacion_cantidad_produccion: '69911111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE-Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad : PE Desviación costo estándar - cantidad',
    cuenta_desviacion_cantidad_produccion_hddn: '6679',
    cuenta_desviacion_precio_produccion: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_produccion_hddn: '6686',
    cuenta_desviacion_precio_compra: '69921111 PE-Costo de ventas-L2 : PE-Desviación costo estándar : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - precio : PE Desviación costo estándar - Precio',
    cuenta_desviacion_precio_compra_hddn: '6686',
  },
}

const arrayLineas = [
  'INYECTABLES',
  'LIQUIDOS',
  'BULK Y PRODUCTOS INTERMEDIOS',
  'SOLIDOS',
  'SEMISOLIDOS',
  'POLVOS',
  'PRODUCTOS INTERMEDIOS TERCEROS', /* oculto */
  'AEROSOL',
  'ALIMENTOS ACTIVOS BIOLOGICOS', /* oculto */
  'PRODUCTO PILOTO',
  'SOLUCIONES TOPICAS',
  'MUESTRAS MEDICAS',
  /*'PRODUCTO INTERMEDIO POLVOS'*/
];