const data_base = [
	{
		linea: "INSTRUMENTOS VETERINARIOS",
		subsidiaria: "2",
		inactivo: false,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "Materia Prima",
		categoria_costo_hddn: "4",
		categoria_costo_indx: "4",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: false,
		cuenta_compras:
			"60111111 PE-Compras-L2 : PE-Mercaderias 60-L3 : PE-Mercaderias 60-L4 : PE-Mercaderias 60111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Compra MERC - Instrumentos Veterinarios L8",
		cuenta_compras_hddn: "5792",
		cuenta_variacion:
			"61111111 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Instrumentos Veterinario L8",
		cuenta_variacion_hddn: "5864",
		tipo_existencia: "01 Mercaderias",
		tipo_existencia_hddn: "1",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "01",
		cod_tipo_existencia_hddn: "01",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69121111 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Instrumentos veterinario L8",
		cuenta_costo_productos_vendidos_hddn: "6227",
		cuenta_activo:
			"20111111 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Instrumentos Veterinarios L8",
		cuenta_activo_hddn: "4789",
		cuenta_ingresos:
			"70121111 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Instrumentos veterinarios L8",
		cuenta_ingresos_hddn: "6339",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MERCHANDISING",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321123 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Merchandising L8",
		cuenta_compras_hddn: "5812",
		cuenta_variacion:
			"61321113 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. existencias SUM NAC - Merchandising L8",
		cuenta_variacion_hddn: "5882",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611123 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Merchandising -L8",
		cuenta_costo_productos_vendidos_hddn: "6762",
		cuenta_activo:
			"25241119 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Merchandising L8",
		cuenta_activo_hddn: "5097",
		cuenta_ingresos:
			"75991116 PE-Otros ingresos de gestion-L2 : PE-Otros ingresos de gestion-L3 : PE-Otros ingresos de gestion 75-L4 : PE-Otros ingresos de gestion 75991-L5 : PE-Otros ingresos de gestión L6 : PE-Otros ingresos de gestión L7 : PE-Otros ingresos L8",
		cuenta_ingresos_hddn: "6473",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MERCADERIA IMPORTADA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "Materia Prima",
		categoria_costo_hddn: "4",
		categoria_costo_indx: "4",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60111112 PE-Compras-L2 : PE-Mercaderias 60-L3 : PE-Mercaderias 60-L4 : PE-Mercaderias 60111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Compra MERC - Medicamentos Veterinarios L8",
		cuenta_compras_hddn: "5793",
		cuenta_variacion:
			"61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8",
		cuenta_variacion_hddn: "5865",
		tipo_existencia: "01 Mercaderias",
		tipo_existencia_hddn: "1",
		catalogo_existencia: "",
		catalogo_existencia_hddn: "",
		catalogo_existencia_indx: "0",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "01",
		cod_tipo_existencia_hddn: "01",
		cod_inventory_catalog: "",
		cod_inventory_catalog_hddn: "",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8",
		cuenta_costo_productos_vendidos_hddn: "6228",
		cuenta_activo:
			"20111112 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Medicamentos Veterinarios L8",
		cuenta_activo_hddn: "4790",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MERCADERIA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60111112 PE-Compras-L2 : PE-Mercaderias 60-L3 : PE-Mercaderias 60-L4 : PE-Mercaderias 60111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Compra MERC - Medicamentos Veterinarios L8",
		cuenta_compras_hddn: "5793",
		cuenta_variacion:
			"61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8",
		cuenta_variacion_hddn: "5865",
		tipo_existencia: "01 Mercaderias",
		tipo_existencia_hddn: "1",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "01",
		cod_tipo_existencia_hddn: "01",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8",
		cuenta_costo_productos_vendidos_hddn: "6228",
		cuenta_activo:
			"20111112 PE-Mercaderias-L2 : PE-Mercaderias 20-L3 : PE-Mercaderias 20-L4 : PE-Costo 20111-L5 : PE-Mercadería Costo L6 : PE-Mercadería Costo L7 : PE-MERC Medicamentos Veterinarios L8",
		cuenta_activo_hddn: "4790",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MATERIALES DE CONSTRUCCION",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "Materia Prima",
		categoria_costo_hddn: "4",
		categoria_costo_indx: "4",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60421111 PE-Compras-L2 : PE-Envases y embalajes 60-L3 : PE-Embalajes 60-L4 : PE-Embalajes 60421-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-Compra Embalajes L8",
		cuenta_compras_hddn: "5835",
		cuenta_variacion:
			"61421111 PE-Variacion de inventarios-L2 : PE-Envases y embalajes 61-L3 : PE-Embalajes 61-L4 : PE-Embalajes 61421-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-Variac. Existencias Embalajes L8",
		cuenta_variacion_hddn: "5904",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69121112 PE-Costo de ventas-L2 : PE-Mercaderias 69-L3 : PE-Mercaderias - venta local 69-L4 : PE-Terceros 69121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Costo de Venta - MERC NAC Medicamentos veterinario L8",
		cuenta_costo_productos_vendidos_hddn: "6228",
		cuenta_activo:
			"26211111 PE-Envases y embalajes-L2 : PE-Embalajes-L3 : PE-Embalajes 26-L4 : PE-Embalajes 26211-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-ME Material de empaque L8",
		cuenta_activo_hddn: "5437",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MATERIAL DE EMPAQUE",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "Materia Prima",
		categoria_costo_hddn: "4",
		categoria_costo_indx: "4",
		utiliza_deposito: true,
		redondear_arriba: true,
		redondear_arriba_remove: "checkbox_unck",
		redondear_arriba_add: "checkbox_ck",
		consumo: true,
		cuenta_compras:
			"60421111 PE-Compras-L2 : PE-Envases y embalajes 60-L3 : PE-Embalajes 60-L4 : PE-Embalajes 60421-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-Compra Embalajes L8",
		cuenta_compras_hddn: "5835",
		cuenta_variacion:
			"61421111 PE-Variacion de inventarios-L2 : PE-Envases y embalajes 61-L3 : PE-Embalajes 61-L4 : PE-Embalajes 61421-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-Variac. Existencias Embalajes L8",
		cuenta_variacion_hddn: "5904",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611114 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de ME - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6830",
		cuenta_activo:
			"26211111 PE-Envases y embalajes-L2 : PE-Embalajes-L3 : PE-Embalajes 26-L4 : PE-Embalajes 26211-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-ME Material de empaque L8",
		cuenta_activo_hddn: "5437",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MUESTRA DE EMPAQUE",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60421111 PE-Compras-L2 : PE-Envases y embalajes 60-L3 : PE-Embalajes 60-L4 : PE-Embalajes 60421-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-Compra Embalajes L8",
		cuenta_compras_hddn: "5835",
		cuenta_variacion:
			"61421111 PE-Variacion de inventarios-L2 : PE-Envases y embalajes 61-L3 : PE-Embalajes 61-L4 : PE-Embalajes 61421-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-Variac. Existencias Embalajes L8",
		cuenta_variacion_hddn: "5904",
		tipo_existencia: "08 Embalajes",
		tipo_existencia_hddn: "8",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "08",
		cod_tipo_existencia_hddn: "08",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611114 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de ME - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6830",
		cuenta_activo:
			"26211111 PE-Envases y embalajes-L2 : PE-Embalajes-L3 : PE-Embalajes 26-L4 : PE-Embalajes 26211-L5 : PE-Embalajes L6 : PE-Embalajes L7 : PE-ME Material de empaque L8",
		cuenta_activo_hddn: "5437",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MUESTRA DE MATERIA PRIMA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60211111 PE-Compras-L2 : PE-Materias primas 60-L3 : PE-Materias primas 60-L4 : PE-Materias primas 60211-L5 : PE-Materias primas L6 : PE-Materias primas L7 : PE-CCompra Materias primas L8",
		cuenta_compras_hddn: "5797",
		cuenta_variacion:
			"61211111 PE-Variacion de inventarios-L2 : PE-Materias primas 61-L3 : PE-Materias primas 61-L4 : PE-Materias primas 61211-L5 : PE-Materias primas L6 : PE-Materias primas L7 : PE-Variac. Existencia Materias primas L8",
		cuenta_variacion_hddn: "5868",
		tipo_existencia: "03 Materias Primas",
		tipo_existencia_hddn: "3",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "10",
		catalogo_existencia_indx: "2",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "03",
		cod_tipo_existencia_hddn: "",
		cod_inventory_catalog: "",
		cod_inventory_catalog_hddn: "",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611111 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6335",
		cuenta_activo:
			"24111111 PE-Materias primas-L2 : PE-Materias primas 24-L3 : PE-Materias primas 24-L4 : PE-Costo 24111-L5 : PE-Materia Prima L6 : PE-Materia Prima L7 : PE-MP Materias Primas L8",
		cuenta_activo_hddn: "5067",
		cuenta_ingresos:
			"70151111 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderías - otras : PE-Terceros : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_ingresos_hddn: "6341",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MUESTRA DE ENVASE",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60411111 PE-Compras-L2 : PE-Envases y embalajes 60-L3 : PE-Envases 60-L4 : PE-Envases 60411-L5 : PE-Envases L6 : PE-Envases L7 : PE-Compra Envases L8",
		cuenta_compras_hddn: "5832",
		cuenta_variacion:
			"61411111 PE-Variacion de inventarios-L2 : PE-Envases y embalajes 61-L3 : PE-Envases 61-L4 : PE-Envases 61411-L5 : PE-Envases L6 : PE-Envases L7 : PE-Variac. Existencias Envases L8",
		cuenta_variacion_hddn: "5902",
		tipo_existencia: "04 Envases",
		tipo_existencia_hddn: "4",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "10",
		catalogo_existencia_indx: "2",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "04",
		cod_tipo_existencia_hddn: "",
		cod_inventory_catalog: "",
		cod_inventory_catalog_hddn: "",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611113 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MV - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6829",
		cuenta_activo:
			"26111111 PE-Envases y embalajes-L2 : PE-Envases-L3 : PE-Envases 26-L4 : PE-Envases 26111-L5 : PE-Envases L6 : PE-Envases L7 : PE-MV Material de envase L8",
		cuenta_activo_hddn: "5417",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MATERIA PRIMA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "Materia Prima",
		categoria_costo_hddn: "4",
		categoria_costo_indx: "4",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60211111 PE-Compras-L2 : PE-Materias primas 60-L3 : PE-Materias primas 60-L4 : PE-Materias primas 60211-L5 : PE-Materias primas L6 : PE-Materias primas L7 : PE-CCompra Materias primas L8",
		cuenta_compras_hddn: "5797",
		cuenta_variacion:
			"61211111 PE-Variacion de inventarios-L2 : PE-Materias primas 61-L3 : PE-Materias primas 61-L4 : PE-Materias primas 61211-L5 : PE-Materias primas L6 : PE-Materias primas L7 : PE-Variac. Existencia Materias primas L8",
		cuenta_variacion_hddn: "5868",
		tipo_existencia: "03 Materias Primas",
		tipo_existencia_hddn: "3",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "03",
		cod_tipo_existencia_hddn: "03",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611111 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6335",
		cuenta_activo:
			"24111111 PE-Materias primas-L2 : PE-Materias primas 24-L3 : PE-Materias primas 24-L4 : PE-Costo 24111-L5 : PE-Materia Prima L6 : PE-Materia Prima L7 : PE-MP Materias Primas L8",
		cuenta_activo_hddn: "5067",
		cuenta_ingresos:
			"70151111 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderías - otras : PE-Terceros : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_ingresos_hddn: "6341",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "MATERIAL DE ENVASADO",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "Materia Prima",
		categoria_costo_hddn: "4",
		categoria_costo_indx: "4",
		utiliza_deposito: true,
		redondear_arriba: true,
		redondear_arriba_remove: "checkbox_unck",
		redondear_arriba_add: "checkbox_ck",
		consumo: true,
		cuenta_compras:
			"60411111 PE-Compras-L2 : PE-Envases y embalajes 60-L3 : PE-Envases 60-L4 : PE-Envases 60411-L5 : PE-Envases L6 : PE-Envases L7 : PE-Compra Envases L8",
		cuenta_compras_hddn: "5832",
		cuenta_variacion:
			"61411111 PE-Variacion de inventarios-L2 : PE-Envases y embalajes 61-L3 : PE-Envases 61-L4 : PE-Envases 61411-L5 : PE-Envases L6 : PE-Envases L7 : PE-Variac. Existencias Envases L8",
		cuenta_variacion_hddn: "5902",
		tipo_existencia: "04 Envases",
		tipo_existencia_hddn: "4",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "04",
		cod_tipo_existencia_hddn: "04",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611113 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MV - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6829",
		cuenta_activo:
			"26111111 PE-Envases y embalajes-L2 : PE-Envases-L3 : PE-Envases 26-L4 : PE-Envases 26111-L5 : PE-Envases L6 : PE-Envases L7 : PE-MV Material de envase L8",
		cuenta_activo_hddn: "5417",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "ARTICULOS PUBLICITARIOS",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321111 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Artículos publicitarios L8",
		cuenta_compras_hddn: "5800",
		cuenta_variacion:
			"61321101 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Artículos publicitar L8",
		cuenta_variacion_hddn: "5870",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "6",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611112 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Artículos publicitarios -L8",
		cuenta_costo_productos_vendidos_hddn: "6750",
		cuenta_activo:
			"25241111 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Artículos publicitarios L8",
		cuenta_activo_hddn: "5089",
		cuenta_ingresos:
			"75991116 PE-Otros ingresos de gestion-L2 : PE-Otros ingresos de gestion-L3 : PE-Otros ingresos de gestion 75-L4 : PE-Otros ingresos de gestion 75991-L5 : PE-Otros ingresos de gestión L6 : PE-Otros ingresos de gestión L7 : PE-Otros ingresos L8",
		cuenta_ingresos_hddn: "6473",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "BROCHURE",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321124 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Brochure L8",
		cuenta_compras_hddn: "5813",
		cuenta_variacion:
			"61321114 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. existencias SUM NAC - Brochure L8",
		cuenta_variacion_hddn: "5883",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "6",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611124 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Brochure -L8",
		cuenta_costo_productos_vendidos_hddn: "6763",
		cuenta_activo:
			"25241112 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Brochure L8",
		cuenta_activo_hddn: "5090",
		cuenta_ingresos:
			"75991116 PE-Otros ingresos de gestion-L2 : PE-Otros ingresos de gestion-L3 : PE-Otros ingresos de gestion 75-L4 : PE-Otros ingresos de gestion 75991-L5 : PE-Otros ingresos de gestión L6 : PE-Otros ingresos de gestión L7 : PE-Otros ingresos L8",
		cuenta_ingresos_hddn: "6473",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "COMESTIBLES",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321112 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Comestibles L8",
		cuenta_compras_hddn: "5801",
		cuenta_variacion:
			"61321102 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Comestibles L8",
		cuenta_variacion_hddn: "5871",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611113 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Comestibles -L8",
		cuenta_costo_productos_vendidos_hddn: "6751",
		cuenta_activo:
			"25241113 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Comestibles L8",
		cuenta_activo_hddn: "5091",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "EQUIPO-MATERIAL DE LABORATORIO",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321114 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Material de laboratorio L8",
		cuenta_compras_hddn: "5803",
		cuenta_variacion:
			"61321104 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Material de laborato L8",
		cuenta_variacion_hddn: "5873",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65711116 PE-Otros gastos de gestion-L2 : PE-Investigación y Desarrollo L3 : PE-Investigación y Desarrollo L4 : PE-Investigación y Desarrollo L5 : PE-Investigación y Desarrollo L6 : PE-Investigación y Desarrollo L7 : PE-Material para ensayo clínico L8",
		cuenta_costo_productos_vendidos_hddn: "6164",
		cuenta_activo:
			"25241118 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Material de laboratorio L8",
		cuenta_activo_hddn: "5096",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "ESTANDAR MATERIA PRIMA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60111112 PE-Compras-L2 : PE-Mercaderias 60-L3 : PE-Mercaderias 60-L4 : PE-Mercaderias 60111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Compra MERC - Medicamentos Veterinarios L8",
		cuenta_compras_hddn: "5793",
		cuenta_variacion:
			"61111112 PE-Variacion de inventarios-L2 : PE-Mercaderias 61-L3 : PE-Mercaderias 61-L4 : PE-Mercaderias 61111-L5 : PE-Mercaderías L6 : PE-Mercaderías L7 : PE-Variac. Existencia MERC - Medicamentos Veterinario L8",
		cuenta_variacion_hddn: "5865",
		tipo_existencia: "03 Materias Primas",
		tipo_existencia_hddn: "3",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "03",
		cod_tipo_existencia_hddn: "03",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"69611111 PE-Costo de ventas-L2 : PE-Mercaderías - otras L3 : PE-Mercaderías - otras : PE-Mercaderías - otras : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_costo_productos_vendidos_hddn: "6335",
		cuenta_activo:
			"24111111 PE-Materias primas-L2 : PE-Materias primas 24-L3 : PE-Materias primas 24-L4 : PE-Costo 24111-L5 : PE-Materia Prima L6 : PE-Materia Prima L7 : PE-MP Materias Primas L8",
		cuenta_activo_hddn: "5067",
		cuenta_ingresos:
			"70151111 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderías - otras : PE-Terceros : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_ingresos_hddn: "6341",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "ESTANDARES DE REFERENCIA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60331112 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Repuestos 60-L4 : PE-Repuestos 60331-L5 : PE-Repuestos Nacional L6 : PE-Repuestos Nacional L7 : PE-Compra NAC Estádar de referencia L8",
		cuenta_compras_hddn: "5829",
		cuenta_variacion:
			"61321115 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. existencias SUM NAC - Estádar de referencia L8",
		cuenta_variacion_hddn: "5884",
		tipo_existencia: "03 Materias Primas",
		tipo_existencia_hddn: "3",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "03",
		cod_tipo_existencia_hddn: "03",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611122 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Estádares de referencias -L8",
		cuenta_costo_productos_vendidos_hddn: "6761",
		cuenta_activo:
			"25241115 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Estándares de referencia L8",
		cuenta_activo_hddn: "5093",
		cuenta_ingresos:
			"70151111 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderías - otras : PE-Terceros : PE-Productos diversos L6 : PE-Productos diversos L7 : PE-Ventas de MP - NAC L8",
		cuenta_ingresos_hddn: "6341",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "FERRETERIA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321115 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Ferretería L8",
		cuenta_compras_hddn: "5804",
		cuenta_variacion:
			"61321105 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Ferretería L8",
		cuenta_variacion_hddn: "5874",
		tipo_existencia: "07 Repuestos",
		tipo_existencia_hddn: "7",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "07",
		cod_tipo_existencia_hddn: "07",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611115 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Ferretería -L8",
		cuenta_costo_productos_vendidos_hddn: "6754",
		cuenta_activo:
			"25241116 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Ferreteria L8",
		cuenta_activo_hddn: "5094",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "HERRAMIENTAS",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321116 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Herramientas L8",
		cuenta_compras_hddn: "5805",
		cuenta_variacion:
			"61321106 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Herramientas L8",
		cuenta_variacion_hddn: "5875",
		tipo_existencia: "07 Repuestos",
		tipo_existencia_hddn: "7",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "07",
		cod_tipo_existencia_hddn: "07",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611125 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Herramientas -L8",
		cuenta_costo_productos_vendidos_hddn: "6764",
		cuenta_activo:
			"25241117 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Herramientas L8",
		cuenta_activo_hddn: "5095",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "REACTIVOS",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321117 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Reactivos L8",
		cuenta_compras_hddn: "5806",
		cuenta_variacion:
			"61321107 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Reactivos L8",
		cuenta_variacion_hddn: "5876",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611116 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Reactivos -L8",
		cuenta_costo_productos_vendidos_hddn: "6755",
		cuenta_activo:
			"25241120 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Reactivos L8",
		cuenta_activo_hddn: "5098",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "REGALOS AL PERSONAL",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321122 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Regalos al personal L8",
		cuenta_compras_hddn: "5811",
		cuenta_variacion:
			"61321112 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Regalos al personal L8",
		cuenta_variacion_hddn: "5881",
		tipo_existencia: "99 Otros",
		tipo_existencia_hddn: "19",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "99",
		cod_tipo_existencia_hddn: "99",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611121 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Regalos al personal -L8",
		cuenta_costo_productos_vendidos_hddn: "6760",
		cuenta_activo:
			"25241121 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Regalos al personal L8",
		cuenta_activo_hddn: "5099",
		cuenta_ingresos:
			"75991116 PE-Otros ingresos de gestion-L2 : PE-Otros ingresos de gestion-L3 : PE-Otros ingresos de gestion 75-L4 : PE-Otros ingresos de gestion 75991-L5 : PE-Otros ingresos de gestión L6 : PE-Otros ingresos de gestión L7 : PE-Otros ingresos L8",
		cuenta_ingresos_hddn: "6473",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "REPUESTOS DE MAQUINARIAS",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60331111 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Repuestos 60-L4 : PE-Repuestos 60331-L5 : PE-Repuestos Nacional L6 : PE-Repuestos Nacional L7 : PE-Compra NAC Repuestos de maquinarias L8",
		cuenta_compras_hddn: "5828",
		cuenta_variacion:
			"61331111 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Repuestos 61-L4 : PE-Repuestos 61331-L5 : PE-Repuestos L6 : PE-Repuestos L7 : PE-Variac. Existencias Repuestos de maquinarias L8",
		cuenta_variacion_hddn: "5900",
		tipo_existencia: "07 Repuestos",
		tipo_existencia_hddn: "07",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "07",
		cod_tipo_existencia_hddn: "07",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611126 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Repuestos de maquinarias -L8",
		cuenta_costo_productos_vendidos_hddn: "6765",
		cuenta_activo:
			"25311111 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Repuestos-L3 : PE-Repuestos 25-L4 : PE-Repuestos 25311-L5 : PE-Repuestos L6 : PE-Repuestos L7 : PE-SD Repuestos de maquinarias L8",
		cuenta_activo_hddn: "5397",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "SUMINISTROS DE COMPUTO",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321118 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Suministros de computo L8",
		cuenta_compras_hddn: "5807",
		cuenta_variacion:
			"61321108 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Suministros de compu L8",
		cuenta_variacion_hddn: "5877",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "6",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611117 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Suministros de cómputo -L8",
		cuenta_costo_productos_vendidos_hddn: "6756",
		cuenta_activo:
			"25241122 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Suministros de cómputo L8",
		cuenta_activo_hddn: "5100",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "SUMINISTROS DE PRODUCCION",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321119 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Suministros de producción L8",
		cuenta_compras_hddn: "5808",
		cuenta_variacion:
			"61321109 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Suministros de produ L8",
		cuenta_variacion_hddn: "5878",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "6",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611118 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Suministros de producción -L8",
		cuenta_costo_productos_vendidos_hddn: "6757",
		cuenta_activo:
			"25241123 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Suministros de producción L8",
		cuenta_activo_hddn: "5101",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "SUMINISTROS VARIOS",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321121 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Suministros varios L8",
		cuenta_compras_hddn: "5810",
		cuenta_variacion:
			"61321111 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Suministros varios L8",
		cuenta_variacion_hddn: "5880",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "6",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611120 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Suministros varios -L8",
		cuenta_costo_productos_vendidos_hddn: "6759",
		cuenta_activo:
			"25241124 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Suministros Varios L8",
		cuenta_activo_hddn: "5102",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "UTILES DE LIMPIEZA",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321120 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Útiles de limpieza L8",
		cuenta_compras_hddn: "5809",
		cuenta_variacion:
			"61321110 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Útiles de limpieza L8",
		cuenta_variacion_hddn: "5879",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "06",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611119 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Útiles de limpieza -L8",
		cuenta_costo_productos_vendidos_hddn: "6758",
		cuenta_activo:
			"25241125 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Útiles de limpieza L8",
		cuenta_activo_hddn: "5103",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
	{
		linea: "ECONOMATO",
		subsidiaria: "2",
		inactivo: true,
		metodo_calculo_costo: "Promedio",
		metodo_calculo_costo_hddn: "AVG",
		metodo_calculo_costo_indx: "0",
		categoria_costo: "No Definido",
		categoria_costo_hddn: "33",
		categoria_costo_indx: "6",
		utiliza_deposito: true,
		redondear_arriba: false,
		redondear_arriba_remove: "checkbox_ck",
		redondear_arriba_add: "checkbox_unck",
		consumo: true,
		cuenta_compras:
			"60321113 PE-Compras-L2 : PE-Materiales auxiliares, suministros y repuestos 60-L3 : PE-Suministros 60-L4 : PE-Suministros 60321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Compra SUM NAC - Economatos L8",
		cuenta_compras_hddn: "5802",
		cuenta_variacion:
			"61321103 PE-Variacion de inventarios-L2 : PE-Materiales auxiliares, suministros y repuestos 61-L3 : PE-Suministros 61-L4 : PE-Suministros 61321-L5 : PE-Suministros diversos Nacional L6 : PE-Suministros diversos Nacional L7 : PE-Variac. Existencias SUM NAC - Economatos L8",
		cuenta_variacion_hddn: "5872",
		tipo_existencia: "06 Suministros",
		tipo_existencia_hddn: "06",
		catalogo_existencia: "CUBSO",
		catalogo_existencia_hddn: "2",
		catalogo_existencia_indx: "6",
		metodo_valuacion: "Promedio Ponderado",
		metodo_valuacion_hddn: "1",
		metodo_valuacion_indx: "7",
		cod_tipo_existencia: "06",
		cod_tipo_existencia_hddn: "06",
		cod_inventory_catalog: "2",
		cod_inventory_catalog_hddn: "2",
		cod_metodo_valuacion: "1",
		cod_metodo_valuacion_hddn: "1",
		cod_cubso: "-",
		cuenta_costo_productos_vendidos:
			"65611111 PE-Otros gastos de gestion-L2 : PE-Suministros -L3 : PE-Suministros -L4 : PE-Suministros -L5 : PE-Suministros -L6 : Suministros -L7 : PE-Economatos -L8",
		cuenta_costo_productos_vendidos_hddn: "6748",
		cuenta_activo:
			"25241114 PE-Materiales auxiliares, suministros y repuestos-L2 : PE-Suministros 2-L3 : PE-Otros suministros 25-L4 : PE-Otros suministros 25241-L5 : PE-Suministros diversos L6 : PE-Suministros diversos L7 : PE-SD Economatos L8",
		cuenta_activo_hddn: "5092",
		cuenta_ingresos:
			"70121112 PE-Ventas-L2 : PE-Mercaderias 70-L3 : PE-Mercaderias - venta local 701-L4 : PE-Mercaderias - venta local 70121-L5 : PE-Mercaderías Nacional L6 : PE-Mercaderías Nacional L7 : PE-Ventas mercaderías NAC - Medicamentos veterinarios L8",
		cuenta_ingresos_hddn: "6340",
		programa_fiscal: "IGV",
		programa_fiscal_hddn: "3",
		programa_fiscal_indx: "3",
	},
];

/*const arrayLineas = [
'INSTRUMENTOS VETERINARIOS',
'MERCHANDISING',
'MERCADERIA IMPORTADA',
'MERCADERIA',
'MATERIALES DE CONSTRUCCION',
'MATERIAL DE EMPAQUE',
'MUESTRA DE EMPAQUE',
'MUESTRA DE MATERIA PRIMA',
'MUESTRA DE ENVASE',
'MATERIA PRIMA',
'MATERIAL DE ENVASADO',
'ARTICULOS PUBLICITARIOS',
'BROCHURE',
'COMESTIBLES',
'EQUIPO-MATERIAL DE LABORATORIO',
'ESTANDAR MATERIA PRIMA',
'ESTANDARES DE REFERENCIA',
'FERRETERIA',
'HERRAMIENTAS',
'REACTIVOS',
'REGALOS AL PERSONAL',
'REPUESTOS DE MAQUINARIAS',
'SUMINISTROS DE COMPUTO',
'SUMINISTROS DE PRODUCCION',
'SUMINISTROS VARIOS',
'UTILES DE LIMPIEZA',
'ECONOMATO'
];*/
